using Luna.Inventory.Application.Reservations;
using Luna.Inventory.Infrastructure;
using Luna.Inventory;
using Microsoft.EntityFrameworkCore;
using Serilog;
using Serilog.Events;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSerilog((context, configuration) => configuration.ReadFrom.Configuration(context.Configuration).Enrich.FromLogContext().Enrich.WithProperty("Service", "Inventory").Filter.ByExcluding(logEvent => logEvent.Properties.TryGetValue("RequestPath", out var requestPath) && requestPath.ToString().Trim('"').Equals("/health", StringComparison.OrdinalIgnoreCase)).WriteTo.Console());
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddInventoryInfrastructure(builder.Configuration);
builder.Services.AddScoped<ReserveInventoryHandler>();
builder.Services.AddScoped<ReleaseReservationHandler>();
builder.Services.AddHealthChecks();
var app = builder.Build();
await app.Services.InitializeInventoryDatabaseAsync();
app.UseSerilogRequestLogging(options => options.GetLevel = (httpContext, _, exception) => httpContext.Request.Path == "/health" ? LogEventLevel.Verbose : exception is not null ? LogEventLevel.Error : LogEventLevel.Information);
app.UseSwagger();
app.UseSwaggerUI();
app.UseMiddleware<InventoryExceptionHandlingMiddleware>();
app.MapControllers();
app.MapHealthChecks("/health");
app.Run();
