using FluentAssertions;
using Luna.Shipping.Domain;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Luna.IntegrationTests.Shipping;

[Collection(ShippingDatabaseCollection.Name)]
public sealed class ShippingDbContextTests(ShippingSqlServerFixture fixture) : IAsyncLifetime
{
    public Task InitializeAsync() => fixture.ResetAsync();

    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task Newly_added_tracking_events_are_marked_for_insert()
    {
        await using var db = fixture.CreateDbContext();
        var shipment = Shipment.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            $"LUNA-DB-{Guid.NewGuid():N}"[..18].ToUpperInvariant(),
            ShipmentRecipientSnapshot.Create(
                Guid.NewGuid(),
                "Jane Doe",
                "1 Main Street",
                null,
                "Austin",
                "Texas",
                "78701",
                "US"));

        db.Shipments.Attach(shipment);
        shipment.MarkInTransit();
        db.ChangeTracker.DetectChanges();

        db.ChangeTracker.Entries<TrackingEvent>()
            .Single(entry => entry.Entity.Status == nameof(ShipmentStatus.InTransit))
            .State
            .Should()
            .Be(EntityState.Added);

        // The insert must survive the real database round trip: tracking event
        // IDs are generated by the domain, and an event EF mistook for an
        // existing row would be reported as an update and silently lost.
        await db.SaveChangesAsync();

        await using var verificationDb = fixture.CreateDbContext();
        var persisted = await verificationDb.Shipments
            .Include(value => value.TrackingEvents)
            .SingleAsync(value => value.Id == shipment.Id);
        persisted.TrackingEvents.Should().ContainSingle(
            value => value.Status == nameof(ShipmentStatus.InTransit));
    }
}
