using FluentAssertions;
using Luna.Shipping.Domain;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Luna.IntegrationTests.Shipping;

[Collection(ShippingDatabaseCollection.Name)]
public sealed class ShippingDbContextTests(ShippingSqlServerFixture fixture) : IAsyncLifetime
{
    /// <summary>
    /// The database is reset as a lifecycle hook rather than as the first statement of each test, so a
    /// test that throws during setup cannot leak rows into the next one.
    /// </summary>
    public Task InitializeAsync() => fixture.ResetAsync();

    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task A_tracking_event_added_to_an_existing_shipment_is_inserted()
    {
        var shipment = await SeedCreatedShipmentAsync();

        await using var db = fixture.CreateDbContext();
        var loaded = await db.Shipments.SingleAsync(value => value.Id == shipment.Id);
        loaded.MarkInTransit();
        db.ChangeTracker.DetectChanges();

        db.ChangeTracker.Entries<TrackingEvent>()
            .Where(entry => entry.Entity.Status == nameof(ShipmentStatus.InTransit))
            .Should().ContainSingle()
            .Which.State.Should().Be(EntityState.Added);

        // Tracking event IDs are generated by the domain rather than by the database, so EF has to treat a
        // newly added event as an insert. If it mistook one for an existing row it would report an update,
        // affect no rows, and throw — which is what the real database round trip below proves. The original
        // version of this test only inspected the change tracker, so it could not have caught that.
        await db.SaveChangesAsync();

        await using var verificationDb = fixture.CreateDbContext();
        var persisted = await verificationDb.Shipments
            .Include(value => value.TrackingEvents)
            .SingleAsync(value => value.Id == shipment.Id);
        persisted.Status.Should().Be(ShipmentStatus.InTransit);
        persisted.TrackingEvents.Select(value => value.Status).Should().BeEquivalentTo(
            [nameof(ShipmentStatus.Created), nameof(ShipmentStatus.InTransit)]);
    }

    private async Task<Shipment> SeedCreatedShipmentAsync()
    {
        var shipment = Shipment.Create(
            Guid.NewGuid(),
            Guid.NewGuid(),
            $"LUNA-DB-{Guid.NewGuid():N}"[..18].ToUpperInvariant(),
            ShipmentRecipientSnapshot.Create(
                Guid.NewGuid(),
                "Jane Doe",
                "1 Main Street",
                null,
                "Austin",
                "Texas",
                "78701",
                "US"));

        await using var db = fixture.CreateDbContext();
        db.Shipments.Add(shipment);
        await db.SaveChangesAsync();
        return shipment;
    }
}
