<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Luna.Payments.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Payments.Contracts\Payments.Contracts.csproj" />
    <ProjectReference Include="..\Payments.Domain\Payments.Domain.csproj" />
  </ItemGroup>
</Project>
