<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Luna.Authentication</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\Luna.Contracts\Luna.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.0.0" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
  </ItemGroup>
</Project>
