// <auto-generated />
using System;
using Luna.Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luna.Inventory.Migrations;

[DbContext(typeof(InventoryDbContext))]
[Migration("20260908160000_AddReservationRowVersion")]
partial class AddReservationRowVersion
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .UseCollation("SQL_Latin1_General_CP1_CI_AS")
            .HasAnnotation("ProductVersion", "8.0.22")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Luna.Inventory.Domain.InventoryReservation", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<Guid>("OrderId").HasColumnType("uniqueidentifier");
            b.Property<byte[]>("RowVersion")
                .IsConcurrencyToken()
                .IsRequired()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("rowversion");
            b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.HasKey("Id");
            b.HasIndex("OrderId").IsUnique();
            b.ToTable("InventoryReservations");
        });

        modelBuilder.Entity("Luna.Inventory.Domain.InventoryReservationItem", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<Guid>("ProductId").HasColumnType("uniqueidentifier");
            b.Property<int>("Quantity").HasColumnType("int");
            b.Property<Guid>("ReservationId").HasColumnType("uniqueidentifier");
            b.HasKey("Id");
            b.HasIndex("ReservationId", "ProductId").IsUnique();
            b.ToTable("InventoryReservationItems");
        });

        modelBuilder.Entity("Luna.Inventory.Domain.Stock", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<Guid>("ProductId").HasColumnType("uniqueidentifier");
            b.Property<int>("QuantityOnHand").HasColumnType("int");
            b.Property<int>("QuantityReserved").HasColumnType("int");
            b.Property<byte[]>("RowVersion")
                .IsConcurrencyToken()
                .IsRequired()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("rowversion");
            b.HasKey("Id");
            b.HasIndex("ProductId").IsUnique();
            b.ToTable("Stocks");
        });

        modelBuilder.Entity("Luna.Inventory.Domain.InventoryReservationItem", b =>
        {
            b.HasOne("Luna.Inventory.Domain.InventoryReservation", null)
                .WithMany("Items")
                .HasForeignKey("ReservationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Luna.Inventory.Domain.InventoryReservation", b =>
        {
            b.Navigation("Items");
        });
#pragma warning restore 612, 618
    }
}
